paths:
  workdir: /data/fankaili/scripts/multi-Omic_workflow/multiome_integration/test_output/
  rna_post_qc_h5ad: /data/fankaili/scripts/multi-Omic_workflow/cell_annotation/test_output/rna_final.h5ad
  atac_post_qc_h5ad: /data/fankaili/scripts/multi-Omic_workflow/ATAC_QC/test_output/atac_h5ad/Muscle_Quadriceps.demo_run.h5ad
  rna_doublet_dir: /data/fankaili/project/dgtex/QC/20250414/Muscle_Quadriceps/RNA/
  atac_doublet_dir: /data/fankaili/scripts/multi-Omic_workflow/ATAC_QC/test_output/
  output_dir: /data/fankaili/scripts/multi-Omic_workflow/multiome_integration/test_output/
  output_h5ad_dir: /data/fankaili/scripts/multi-Omic_workflow/multiome_integration/test_output/h5ad/
  sample_metadata: /data/fankaili/scripts/multi-Omic_workflow/ATAC_QC/test_data/test_metatable.txt

references:
  gencode_gtf: /data/fankaili/scripts/multi-Omic_workflow/ATAC_QC/ref/gencode.v47.primary_assembly.annotation.gtf
  chrom_size: /data/fankaili/ref/chromsize/hg38.chrom.sizes

params:
  tissue: Muscle - Quadriceps
  suffix: Muscle_Quadriceps
  n_threads: 16
  n_features: 50000
  peak_half_width: 150
  celltype_col: manual_fine_annotation0
  celllineage_col: manual_broad_annotation
  imputation: True

color:
    tissue_colors: 
        "Kidney": "#a32015"
        "Liver - Left Lobe": "#AABB66"
        "Lung - Left Cranial Lobe": "#99FF00"
        "Muscle - Gastrocnemius": "#9191ff"
        "Muscle - Quadriceps": "#5e5eff"
        "Thyroid": "#006600"
        "Adrenal Gland": "#33DD33"
        "Adipose - Subcutaneous": "#1d8c46"
    donor_colors:
        DGTEX002: "#E73A2F"
        DGTEX031: "#65c4ff"
        DGTEX008: "#FBB30B"
        DGTEX047: "#2E9E49"
        DGTEX001: "#397AF2"
        DGTEX027: "#8e02da"

my_color_palette:
  - "#c50909"
  - "#ffa806"
  - "#fbe95d"
  - "#16b900"
  - "#65c4ff"
  - "#0e3aa9"
  - "#8e02da"
  - "#795548"
  - "#9E9E9E"
  - "#ff5b13"
  - "#154f11"
  - "#8bc34a"
  - "#ff37a6"
  - "#0062ff"
  - "#00bfae"
  - "#ea9c28"
  - "#6e7f27"
  - "#43e8e6"
  - "#a4ff5a"
  - "#e72c80"